### ISSUE TITLE
Plugin does not have a valid header

### ISSUE THREAD

**Issue by justinwilson** [TimBHowe/gravityforms-emailblacklist#8]
Wordpress deactivates the plugin when trying to install it. "Plugin does not have a valid header". Would be great to try this one out once it's compatible with the new WP.

**Comment by TimBHowe** [comment]
Looking into the issue. I'm hoping it will be resolved in the 2.0 release.

**Comment by TimBHowe** [comment]
This should now be resolved in 2.1.
